### ISSUE TITLE
java.lang.NoSuchFieldError: writableBinaryObjectInspector while running the udaf

### ISSUE THREAD

**Issue by Rajknandy** [MLnick/hive-udf#1]
I have built the "hive-udf-0.0.1-SNAPSHOT.jar" using Maven. After building, I ran it in local mode. But I am getting  "java.lang.NoSuchFieldError"

Error Stack :

hive> select approx_distinct(last_name, 'lc').cardinality from default.customers;
Exception in thread "main" java.lang.NoSuchFieldError: writableBinaryObjectInspector
    at com.github.mlnick.hive.udaf.UDAFCardinalityEstimator$CardinalityEstimatorEvaluator.init(UDAFCardinalityEstimator.java:208)
    at org.apache.hadoop.hive.ql.parse.SemanticAnalyzer.getGenericUDAFInfo(SemanticAnalyzer.java:2184)
    at org.apache.hadoop.hive.ql.parse.SemanticAnalyzer.genGroupByPlanMapGroupByOperator(SemanticAnalyzer.java:2586)
    at org.apache.hadoop.hive.ql.parse.SemanticAnalyzer.genGroupByPlanMapAggr1MR(SemanticAnalyzer.java:3157)
    at org.apache.hadoop.hive.ql.parse.SemanticAnalyzer.genBodyPlan(SemanticAnalyzer.java:5425)
    at org.apache.hadoop.hive.ql.parse.SemanticAnalyzer.genPlan(SemanticAnalyzer.java:6021)
    at org.apache.hadoop.hive.ql.parse.SemanticAnalyzer.analyzeInternal(SemanticAnalyzer.java:6606)
    at org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer.analyze(BaseSemanticAnalyzer.java:238)
    at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:340)
    at org.apache.hadoop.hive.ql.Driver.run(Driver.java:736)
    at org.apache.hadoop.hive.cli.CliDriver.processCmd(CliDriver.java:209)
    at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:286)
    at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:516)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:197)

Please help.

**Comment by MLnick** [comment]
Hi,

Did you do the following to add the UDF in your Hive CLI?

```
hive> add jar hive-udf-0.0.1-SNAPSHOT.jar;
hive> create temporary function approx_distinct as 'com.github.mlnick.hive.udaf.UDAFCardinalityEstimator';
```

Could you also post what Hive version you're using and the fields in your input table?

**Comment by Rajknandy** [comment]
Hi,
We were working with hive-0.7.0 .Thats why we were getting this error.
Now it is resolved as we executed it in CDH4 cluster with hive-0.9.0.
Now it is working fine.

Thanks for replying.

**Comment by MLnick** [comment]
Great! thanks
