### ISSUE TITLE
Java heap space issue with large cardinality / bigger datasets

### ISSUE THREAD

**Issue by tgiridhar** [MLnick/hive-udf#3]
The UDAF works great for lower cardinality and integer numbers but as soon as i run it on billions of rows with bigint i run into the following error.

java.lang.Exception: java.lang.OutOfMemoryError: Java heap space
at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:404)
Caused by: java.lang.OutOfMemoryError: Java heap space
at org.apache.hadoop.mapred.MapTask$MapOutputBuffer.init(MapTask.java:826)
at org.apache.hadoop.mapred.MapTask.createSortingCollector(MapTask.java:376)
at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:406)
at org.apache.hadoop.mapred.MapTask.run(MapTask.java:332)
at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
at java.util.concurrent.FutureTask.run(FutureTask.java:138)
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
at java.lang.Thread.run(Thread.java:662)

I did set mapred.child.java.opts=-Xmx8000m and it still fails. I am wondering if there is a memory leak issue or something. Is there a way to debug the UDAF?

**Comment by MLnick** [comment]
Hmmm will take a look. Could be a memory leak or perhaps with large datasets something around merging all the intermediate HLL instances.

Unfortunately Hive UDFs are really tricky to debug and even test!
—

**Comment by tgiridhar** [comment]
Thank you and I appreciate your time. In the meantime, i will go and test
the clearspring routines to see if they have any memory leak or GC issues.

**Comment by MLnick** [comment]
Something that might work is to try increasing the split size in Hadoop thus decreasing the effective number of mappers - this could potentially alleviate the intermediate merging pressure (in case that is an issue). Worth a shot perhaps.
—

**Comment by tgiridhar** [comment]
Thank you for the suggestion, i tried split between 16M to 4GB and the
error was still there. I tried running this from beeswax (hive UI) and
looking at the logs this time showed a different error

more Caused by: java.lang.NullPointerException at
com.github.mlnick.hive.udaf.UDAFCardinalityEstimator$CardinalityEstimatorEvaluator.terminatePartial(UDAFCardinalityEstimator.java:280)
at
org.apache.hadoop.hive.ql.udf.generic.GenericUDAFEvaluator.evaluate(GenericUDAFEvaluator.java:155)
at
org.apache.hadoop.hive.ql.exec.GroupByOperator.forward(GroupByOperator.java:1058)
at
org.apache.hadoop.hive.ql.exec.GroupByOperator.flush(GroupByOperator.java:1027)
at
org.apache.hadoop.hive.ql.exec.GroupByOperator.processHashAggr(GroupByOperator.java:866)
at
org.apache.hadoop.hive.ql.exec.GroupByOperator.processKey(GroupByOperator.java:751)
at
org.apache.hadoop.hive.ql.exec.GroupByOperator.processOp(GroupByOperator.java:819)
... 18 more

public Object terminatePartial(AggregationBuffer aggregationBuffer) throws
HiveException {
            CardinalityEstimatorBuffer ceb = (CardinalityEstimatorBuffer)
aggregationBuffer;
            try {
                byte[] tb = ce.name().getBytes("UTF-8");
280:          byte[] ceBytes = ceb.cardinalityEstimator.getBytes();
                List<BytesWritable> b = new ArrayList<BytesWritable>();
                b.add(new BytesWritable(tb));
                b.add(new BytesWritable(ceBytes));
                return b;
            } catch (IOException e) {
                throw new HiveException("Failed to extract byte[] during
partial termination. ", e);
            }
        }

**Comment by MLnick** [comment]
Hi

Sorry for the long delay - been swamped and I no longer use Hive these days. I'll try to take a look if I get time. But it seems maybe there was no aggregation buffer so maybe a null check would suffice. What was the split when you got the error?

Also I noticed that Clearspring has done quite a lot of work on streamlib including adding new HLL++ and improving memory and merge efficiency. May be worth trying to bump up to the latest streamlib version and see if that helps HLL performance (https://github.com/clearspring/stream-lib).

@abramsm might have some other ideas about what is going on.

Sorry I can't be more helpful right now I just don't have spare time at the moment (and all my work is done in Scala and Spark these days :))

**Comment by abramsm** [comment]
I do recommend upgrading to HLL+ it provides some memory efficiencies over
the original HLL implementation.  The number of entries in a HLL (or HLL+)
has very little impact on retained memory size.  In addition merging HLL
objects only requires 2 HLL instances to be in memory at any given time so
I'm not sure how that could cause the leak.  Sorry I can't be of more help
but I'm not really familiar with this implementation or Hive.

matt

**Comment by tgiridhar** [comment]
Matt,

Thanks a lot for getting back on this issue. I appreciate you taking time
inspite of not being actively working on this. I did try with HLL+ and it
seems to error out again at the same place with an empty aggregation
bufffer. My guess is that there are out of memory issues inside Hive
framework or the way Hive calls the aggregation routine. Now, I am looking
to see if https://gist.github.com/travisbrady/4498040 is any better with
memory usage compared to HLL.

Cheers,
Giri
